### ISSUE TITLE
v2.0.2 --- unable to trigger any macros....

### ISSUE THREAD

**Issue by karpana** [ardittristan/HookMacros#7]
I couldn't figure out why the last few weeks, my triggers (which were being run via journals) weren't working.  I realized that I updated to v2.0.2 about that time, and just learned today, that the interface for managing/overseeing HookMacros has completely changed.

The side effect of this, and  hence the reason for this issue, is to advise, that I'm unable to trigger ANY macros, whether via the Settings, Local Settings or the Legacy Journal approach.

I've tried the following very simple configurations

Settings variation 1
- Hook name:   updateToken
- Macro name:  hpChange
- Macro Arguments: none

Settings variation 2
- Hook name:   updateToken
- Macro name:  hpChange
- Macro Arguments: arg1,arg2,arg3

Settings variation 3
- Hook name:   updateCombat
- Macro name:  Sanity Trigger            ---Note: this was fully functional in the Journal configuration model
- Macro Arguments: arg1

Local Settings variation 1
- Hook name:   updateToken
- Macro name:  hpChange
- Macro Arguments: none

Local Settings variation 2
- Hook name:   updateToken
- Macro name:  hpChange
- Macro Arguments: arg1,arg2,arg3

Local Settings variation 3
- Hook name:   updateCombat
- Macro name:  Sanity Trigger        ---Note: this was fully functional in the Journal configuration model
- Macro Arguments: arg1

**Comment by ardittristan** [comment]
is there any kind of error showing up in the console? (F12)

**Comment by karpana** [comment]
after getting really frustrated at this... I restarted the foundry instance (on my Rpi Server)...
and lo it started to work...

I've fuddled around with a bunch of different things and here are my observations

1) local settings doesn't seem to work at all... (not sure why)
2) if I change anything in "Settings" or "Enable legacy journal settings", I have to (at minimum) hit F5 to refresh Foundry. 
3) macro arguments (in Settings) seem to do nothing but add extra arguments in front of the default arguments that seem to get passed through automatically.

What I have now... is this

Settings (not in local Settings)
Macro Hook # 1
- updateToken
- hpChange
- <blank>

Macro Hook # 2
- updateCombat
- Sanity Trigger
- <blank>           (when I do this, I still get the expected arguments passed in...)

local Settings
***NOTHING*

Legacy Journal
- unchecked


and it seems to be working... for a while...

and then **_randomly_** in the user messages area of the console, I see this...
`hookmacro.js:15 Emergency mode enabled! Hook macros stopped running.
(anonymous) @ hookmacro.js:15`

it also shows up in Mesages & error....

from that point onwards ...  none of the macros run... until I hit F5 again....

**Comment by karpana** [comment]
I'm wondering if the "emergency mode" is being activated because the hooked macro itself throws an error?
not sure...

I know I"m developing the macro ... but the activation of emergency mode seems random...

**Comment by ardittristan** [comment]
Emergency mode gets activated when the end key gets pressed

**Comment by karpana** [comment]
just by touching the end key at any point while using this?  or while the session is being started?
(because I haven't been holding the end key at any point during start up)

**Comment by ardittristan** [comment]
at any point, though I should probably turn it off after a minute or two

**Comment by karpana** [comment]
yeah... that really needs to be turned off...
because if I'm trying to type and edit a message (or in my case ... edit macros) ...  i'm all kinds of keys on my keyboard... home, end, pgup, pgdown....

(it's really frustrating when I'm trying to build the macro and the use of the end key kills the whole thing....)

**Comment by karpana** [comment]
if you want ... we can close this issue down ... and create another issue for the end key...

the end key is a nice feature for when something breaks... but it shouldn't "activate" once things are running cleanly...

**Comment by karpana** [comment]
I'm not sure if there's a point in the "load up sequence" where you can tell from your module that things are running or not...
but I guess in a pinch, a timer is probably a decent workaround

**Comment by ardittristan** [comment]
I'll put the timer on 1 minute, and also fix the local hooks not running in an update in a sec, if you still experience issues after the update please say so!

**Comment by ardittristan** [comment]
release should be live

**Comment by karpana** [comment]
just pulled it down... will start playing with it in a few moments... 

what's the intended difference between "settings" and "local settings"?

**Comment by ardittristan** [comment]
settings are for everyone, and local settings is only for that browser (same as world and client settings)

**Comment by karpana** [comment]
very cool ... so does a "local setting" *only* apply to my browser if I set it?
or does it get setup for all the browsers?

(just trying to determine if this hpChange macro (and the Sanity Trigger I've already written),  should be a setting or a local setting.  I only need/want them running when I'm in the GM seat.

**Comment by ardittristan** [comment]
only your browser, but it doesn't distinguish between users, so any users in that browser instance (unless you remove your local storage, then it's gone) though that's how all foundry client settings work

**Comment by karpana** [comment]
that's cool... in these these particular campaigns, I'm only a GM, so it should be okay...

**Comment by karpana** [comment]
I just did a quick test of the "end" button...

I waited for 1minute 20 seconds before pressing the end key, and the "emergency mode" message came up..  (which was unexpected...)

I did confirm I have 2.0.3 installed

**Comment by karpana** [comment]
is this code in seconds, because if so, 3600 seconds is 1 hour...

`setTimeout(() => {
    window.removeEventListener(emergencyEvent);
  }, 3600);`

**Comment by ardittristan** [comment]
nah, the issue was that I forgot to supply the event type ("keydown"), javascript times in miliseconds (which still makes it wrong, but only 3.6 seconds)

**Comment by ardittristan** [comment]
update should be live in a sec

**Comment by karpana** [comment]
Had to step out for a few minutes ... Will check shortly.

**Comment by karpana** [comment]
gave 2.0.4 a whirl...
seems like we're back in business (in terms of the timeout issue).
I haven't tested "local settings" yet.  

But i'll give that a whirl in the coming days.
First, I need to find out why my HP edits aren't triggering multiple macro events... (even though movement does...)
(i think this is a problem with the *Token Health* module, and not something your module is doing)
